__BASE__: configs/GQ_Nets/resnet50_vanilla.yaml

wrapper:
  name: ParametrizedQuantWrapper
  args:
    quant_conf:
      bit_width: 5

work_dir: /mnt/lustre/lirundong/Workspace/GQ-Nets/res50-vanilla-w5a5/
resume: /mnt/lustre/lirundong/Workspace/GQ-Nets/res50-vanilla-w5a5/latest.pth
