__BASE__: configs/GQ_Nets/resnet20_cifar10_vanilla.yaml

dataset:
  args:
    root: /mnt/lustre/lirundong/Data/Datasets/CIFAR

train:
  ckpt_interval: null
  qat_policies:
    - name: SetupQuantOnce
      args:
        quant_mode:
          - quant
          - fp
        calibrate_cfg:
          name: calibration
          type: ActivationCalibration
          args:
            percentile: 0.99
    - name: ConstantVariable
      args:
        name: ce_loss_weight
        value: 1.0
    - name: ConstantVariable
      args:
        name: kl_loss_weight
        value: 1.0
    - name: ConstantVariable
      args:
        name: kl_temperature
        value: 1.0
    - name: OptimAlterStep
      args:
        apply_to:
          - weight_params
          - quant_params
        alter_freq: -1
        intervals:
          - [0, -1]
    - name: RAMBufferedCheckpoint
      args:
        criterion: quant_top1_eval_acc
        interval: 10

runtime_hooks: null
work_dir: /mnt/lustre/lirundong/Data/Experiments/GQ-Nets/resnet20-cifar10-vanilla-pretrained-w4a4
resume: /mnt/lustre/lirundong/Data/Experiments/GQ-Nets/resnet20-cifar10-vanilla-pretrained-w4a4/ckpt_best.pth
fresh_resume: /mnt/lustre/lirundong/Data/Experiments/resnet20-cifar10/epoch_200.pth
